// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQFv61-wdvLp-87Y26OqE39_TaZqef3rE',
    appId: '1:622694521192:web:af6670e0dd726ddb739edd',
    messagingSenderId: '622694521192',
    projectId: 'better-health1',
    authDomain: 'better-health1.firebaseapp.com',
    storageBucket: 'better-health1.appspot.com',
    measurementId: 'G-M2MNBGTTC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDvdB-7C8j2-ml9SuIJyRHyW4gg1vAPLQ',
    appId: '1:622694521192:android:e29204806966d4b2739edd',
    messagingSenderId: '622694521192',
    projectId: 'better-health1',
    storageBucket: 'better-health1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwD74rcoZ-xOQ3OXhSxJf2FbFeEVt34aA',
    appId: '1:622694521192:ios:07ca4f0c6b23033d739edd',
    messagingSenderId: '622694521192',
    projectId: 'better-health1',
    storageBucket: 'better-health1.appspot.com',
    iosClientId: '622694521192-u82go5coj73oqc86704dhltflj0iesl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.betterHealth',
  );
}
